export const Events = {
  SMS_RETRIVED: 'SMS_RETRIEVED',
  SMS_RETRIEVE_ERROR: 'SMS_RETRIEVE_ERROR',
};

export enum Errors {
  NULL_ACTIVITY,
  NULL_BROADCAST_RECEIVER,
  COULD_NOT_HANDLE_BROADCAST,
  CONSENT_TIMEOUT,
  CONSENT_CANCELED,
}
